In [1]:
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


In [2]:
wine=datasets.load_wine()
x,y=wine.data,wine.target
#递归特征消除需要给一个评价模型，评价模型需要能给出特征重要程度，比如线性回归，SVR
estimator=LogisticRegression()
selector=RFE(estimator, n_features_to_select=8, step=1).fit(x,y)
print('selector.support_\n',selector.support_)
print('selector.ranking_\n',selector.ranking_)
print('selector.estimator_\n',selector.estimator_)

selector.support_
 [False  True  True  True False False  True False  True  True  True  True
 False]
selector.ranking_
 [4 1 1 1 5 3 1 2 1 1 1 1 6]
selector.estimator_
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [3]:
l=len(x[0])
wine_feature=[]
for i in range(l):
    if selector.support_[i]:
        wine_feature.append(i)
print(wine_feature)
#线性回归筛选结果：[1, 2, 3, 6, 8, 9, 10, 11]

[1, 2, 3, 6, 8, 9, 10, 11]


## 支持向量机分类结果

In [4]:
from sklearn.svm import SVR
import time
start = time.clock()
elapsed = (time.clock() - start)

estimator=SVR(kernel='linear')
selector2=RFE(estimator,8,step=1).fit(x,y)
print('selector.ranking_\n',selector.ranking_)
l=len(x[0])
wine_feature=[]
for i in range(l):
    if selector2.support_[i]:
        wine_feature.append(i)
print(wine_feature)
print("Time used:",elapsed)
#筛选结果为[0, 2, 3, 5, 6, 7, 10, 11]，而且耗时很长

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  after removing the cwd from sys.path.


selector.ranking_
 [4 1 1 1 5 3 1 2 1 1 1 1 6]
[0, 2, 3, 5, 6, 7, 10, 11]
Time used: 0.00028064999999966034


In [7]:
#也是线性支持向量机，效果一样
from sklearn.svm import LinearSVC
from sklearn.preprocessing import StandardScaler
import numpy as np
#这里开始要计算运行时间了
import time
start = time.clock()
elapsed = (time.clock() - start)
#数据标准化后对比效果
#scaler = StandardScaler()
#scaler.fit(x)
#终于知道如何取特征名称了
featureNames = wine.feature_names
estimator=LinearSVC()
selector3=RFE(estimator,8,step=1).fit(x,y)
print('selector.ranking_\n',selector3.ranking_)
l=len(x[0])
wine_feature=[]
for i in range(l):
    if selector3.support_[i]:
        wine_feature.append(i)
#用np.array，加一个布尔列表，来取特征        
feats = list(np.array(featureNames)[selector3.support_])
print('choosed features:\n',feats)
print(wine_feature)
#输出时间
print("Time used:",elapsed)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


selector.ranking_
 [4 2 1 1 5 3 1 1 1 1 1 1 6]
choosed features:
 ['ash', 'alcalinity_of_ash', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines']
[2, 3, 6, 7, 8, 9, 10, 11]
Time used: 0.00016302200000950506
